name: salud_flutter
description: Aplicación profesional para control de ejercicios con persistencia local y preparada para Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management (lo más moderno)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Base de datos local (más moderna y rápida)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  
  # Calendario
  table_calendar: ^3.1.1
  
  # Gráficas profesionales
  fl_chart: ^0.68.0
  
  # Utilidades
  intl: ^0.19.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  
  # Icon generation and image processing
  flutter_launcher_icons: ^0.13.1
  image: ^4.2.0

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: assets/icon/icon.png
  image_path_android: assets/icon/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/icon.png

flutter:
  uses-material-design: true
  
  # Assets para el futuro
  # assets:
  #   - assets/images/
  #   - assets/icons/
