import '../models/alimento.dart';

/// Biblioteca de alimentos comunes con valores nutricionales
/// Valores por 100g o unidad estándar
class AlimentosComunes {
  static List<AlimentoBase> obtenerAlimentosBase() {
    return [
      // ========== FRUTAS ==========
      _crearAlimento(
        nombre: 'Manzana',
        calorias: 52,
        proteinas: 0.3,
        carbohidratos: 14,
        grasas: 0.2,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'frutas',
        icono: 'apple',
        color: '#EF4444',
      ),
      _crearAlimento(
        nombre: 'Plátano',
        calorias: 89,
        proteinas: 1.1,
        carbohidratos: 23,
        grasas: 0.3,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'frutas',
        icono: 'banana',
        color: '#F59E0B',
      ),
      _crearAlimento(
        nombre: 'Naranja',
        calorias: 47,
        proteinas: 0.9,
        carbohidratos: 12,
        grasas: 0.1,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'frutas',
        icono: 'orange',
        color: '#F97316',
      ),
      _crearAlimento(
        nombre: 'Fresa',
        calorias: 32,
        proteinas: 0.7,
        carbohidratos: 8,
        grasas: 0.3,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'frutas',
        icono: 'strawberry',
        color: '#EC4899',
      ),
      _crearAlimento(
        nombre: 'Aguacate',
        calorias: 160,
        proteinas: 2,
        carbohidratos: 9,
        grasas: 15,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'frutas',
        icono: 'avocado',
        color: '#10B981',
      ),

      // ========== PROTEÍNAS ==========
      _crearAlimento(
        nombre: 'Pechuga de pollo',
        calorias: 165,
        proteinas: 31,
        carbohidratos: 0,
        grasas: 3.6,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'proteinas',
        icono: 'chicken',
        color: '#F59E0B',
      ),
      _crearAlimento(
        nombre: 'Huevo entero',
        calorias: 155,
        proteinas: 13,
        carbohidratos: 1.1,
        grasas: 11,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'proteinas',
        icono: 'egg',
        color: '#FDE047',
      ),
      _crearAlimento(
        nombre: 'Huevo (unidad)',
        calorias: 78,
        proteinas: 6.3,
        carbohidratos: 0.6,
        grasas: 5.3,
        cantidad: 1,
        unidad: 'unidad',
        categoria: 'proteinas',
        icono: 'egg',
        color: '#FDE047',
      ),
      _crearAlimento(
        nombre: 'Atún en agua',
        calorias: 116,
        proteinas: 26,
        carbohidratos: 0,
        grasas: 0.8,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'proteinas',
        icono: 'fish',
        color: '#3B82F6',
      ),
      _crearAlimento(
        nombre: 'Carne de res magra',
        calorias: 250,
        proteinas: 26,
        carbohidratos: 0,
        grasas: 15,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'proteinas',
        icono: 'beef',
        color: '#DC2626',
      ),
      _crearAlimento(
        nombre: 'Salmón',
        calorias: 208,
        proteinas: 20,
        carbohidratos: 0,
        grasas: 13,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'proteinas',
        icono: 'salmon',
        color: '#F97316',
      ),

      // ========== LÁCTEOS ==========
      _crearAlimento(
        nombre: 'Leche entera',
        calorias: 61,
        proteinas: 3.2,
        carbohidratos: 4.8,
        grasas: 3.3,
        cantidad: 100,
        unidad: 'ml',
        categoria: 'lacteos',
        icono: 'milk',
        color: '#FFFFFF',
      ),
      _crearAlimento(
        nombre: 'Yogurt natural',
        calorias: 59,
        proteinas: 10,
        carbohidratos: 3.6,
        grasas: 0.4,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'lacteos',
        icono: 'yogurt',
        color: '#FBBF24',
      ),
      _crearAlimento(
        nombre: 'Queso panela',
        calorias: 239,
        proteinas: 24,
        carbohidratos: 3,
        grasas: 15,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'lacteos',
        icono: 'cheese',
        color: '#FDE68A',
      ),

      // ========== GRANOS Y CEREALES ==========
      _crearAlimento(
        nombre: 'Arroz blanco cocido',
        calorias: 130,
        proteinas: 2.7,
        carbohidratos: 28,
        grasas: 0.3,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'granos',
        icono: 'rice',
        color: '#F5F5F5',
      ),
      _crearAlimento(
        nombre: 'Pasta cocida',
        calorias: 131,
        proteinas: 5,
        carbohidratos: 25,
        grasas: 1.1,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'granos',
        icono: 'pasta',
        color: '#FDE047',
      ),
      _crearAlimento(
        nombre: 'Pan integral',
        calorias: 247,
        proteinas: 13,
        carbohidratos: 41,
        grasas: 3.4,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'granos',
        icono: 'bread',
        color: '#92400E',
      ),
      _crearAlimento(
        nombre: 'Avena cruda',
        calorias: 389,
        proteinas: 17,
        carbohidratos: 66,
        grasas: 7,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'granos',
        icono: 'oatmeal',
        color: '#FEF3C7',
      ),
      _crearAlimento(
        nombre: 'Tortilla de maíz',
        calorias: 218,
        proteinas: 5.7,
        carbohidratos: 45,
        grasas: 2.8,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'granos',
        icono: 'tortilla',
        color: '#FDE68A',
      ),

      // ========== VERDURAS ==========
      _crearAlimento(
        nombre: 'Brócoli',
        calorias: 34,
        proteinas: 2.8,
        carbohidratos: 7,
        grasas: 0.4,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'verduras',
        icono: 'broccoli',
        color: '#10B981',
      ),
      _crearAlimento(
        nombre: 'Espinaca',
        calorias: 23,
        proteinas: 2.9,
        carbohidratos: 3.6,
        grasas: 0.4,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'verduras',
        icono: 'spinach',
        color: '#059669',
      ),
      _crearAlimento(
        nombre: 'Zanahoria',
        calorias: 41,
        proteinas: 0.9,
        carbohidratos: 10,
        grasas: 0.2,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'verduras',
        icono: 'carrot',
        color: '#F97316',
      ),
      _crearAlimento(
        nombre: 'Tomate',
        calorias: 18,
        proteinas: 0.9,
        carbohidratos: 3.9,
        grasas: 0.2,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'verduras',
        icono: 'tomato',
        color: '#EF4444',
      ),

      // ========== LEGUMINOSAS ==========
      _crearAlimento(
        nombre: 'Frijoles negros cocidos',
        calorias: 132,
        proteinas: 8.9,
        carbohidratos: 24,
        grasas: 0.5,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'leguminosas',
        icono: 'beans',
        color: '#1F2937',
      ),
      _crearAlimento(
        nombre: 'Lentejas cocidas',
        calorias: 116,
        proteinas: 9,
        carbohidratos: 20,
        grasas: 0.4,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'leguminosas',
        icono: 'lentils',
        color: '#92400E',
      ),
      _crearAlimento(
        nombre: 'Garbanzos cocidos',
        calorias: 164,
        proteinas: 8.9,
        carbohidratos: 27,
        grasas: 2.6,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'leguminosas',
        icono: 'chickpeas',
        color: '#FDE68A',
      ),

      // ========== FRUTOS SECOS ==========
      _crearAlimento(
        nombre: 'Almendras',
        calorias: 579,
        proteinas: 21,
        carbohidratos: 22,
        grasas: 50,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'frutos_secos',
        icono: 'almond',
        color: '#92400E',
      ),
      _crearAlimento(
        nombre: 'Nueces',
        calorias: 654,
        proteinas: 15,
        carbohidratos: 14,
        grasas: 65,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'frutos_secos',
        icono: 'walnut',
        color: '#78350F',
      ),
      _crearAlimento(
        nombre: 'Cacahuates',
        calorias: 567,
        proteinas: 26,
        carbohidratos: 16,
        grasas: 49,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'frutos_secos',
        icono: 'peanut',
        color: '#C2410C',
      ),

      // ========== SNACKS Y OTROS ==========
      _crearAlimento(
        nombre: 'Chocolate oscuro (70%)',
        calorias: 598,
        proteinas: 7.8,
        carbohidratos: 46,
        grasas: 43,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'snacks',
        icono: 'chocolate',
        color: '#78350F',
      ),
      _crearAlimento(
        nombre: 'Aceite de oliva',
        calorias: 884,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 100,
        cantidad: 100,
        unidad: 'ml',
        categoria: 'aceites',
        icono: 'oil',
        color: '#84CC16',
      ),
      _crearAlimento(
        nombre: 'Miel',
        calorias: 304,
        proteinas: 0.3,
        carbohidratos: 82,
        grasas: 0,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'endulzantes',
        icono: 'honey',
        color: '#F59E0B',
      ),

      // ========== COMIDA MEXICANA ==========
      _crearAlimento(
        nombre: 'Taco de carne asada',
        calorias: 226,
        proteinas: 12,
        carbohidratos: 20,
        grasas: 11,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_mexicana',
        icono: 'taco',
        color: '#F59E0B',
      ),
      _crearAlimento(
        nombre: 'Enchiladas verdes',
        calorias: 186,
        proteinas: 9,
        carbohidratos: 18,
        grasas: 9,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_mexicana',
        icono: 'enchilada',
        color: '#10B981',
      ),
      _crearAlimento(
        nombre: 'Quesadilla de queso',
        calorias: 312,
        proteinas: 15,
        carbohidratos: 28,
        grasas: 15,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_mexicana',
        icono: 'quesadilla',
        color: '#FDE68A',
      ),
      _crearAlimento(
        nombre: 'Tamales de pollo',
        calorias: 223,
        proteinas: 9,
        carbohidratos: 32,
        grasas: 7,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_mexicana',
        icono: 'tamal',
        color: '#92400E',
      ),
      _crearAlimento(
        nombre: 'Pozole rojo',
        calorias: 134,
        proteinas: 12,
        carbohidratos: 15,
        grasas: 3,
        cantidad: 100,
        unidad: 'ml',
        categoria: 'comida_mexicana',
        icono: 'pozole',
        color: '#DC2626',
      ),
      _crearAlimento(
        nombre: 'Chilaquiles verdes',
        calorias: 165,
        proteinas: 7,
        carbohidratos: 18,
        grasas: 7,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_mexicana',
        icono: 'chilaquiles',
        color: '#059669',
      ),
      _crearAlimento(
        nombre: 'Torta de jamón',
        calorias: 245,
        proteinas: 12,
        carbohidratos: 32,
        grasas: 8,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_mexicana',
        icono: 'torta',
        color: '#FDE68A',
      ),
      _crearAlimento(
        nombre: 'Gorditas de chicharrón',
        calorias: 298,
        proteinas: 11,
        carbohidratos: 35,
        grasas: 13,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_mexicana',
        icono: 'gordita',
        color: '#92400E',
      ),
      _crearAlimento(
        nombre: 'Sopes de frijol',
        calorias: 178,
        proteinas: 7,
        carbohidratos: 26,
        grasas: 5,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_mexicana',
        icono: 'sope',
        color: '#1F2937',
      ),
      _crearAlimento(
        nombre: 'Guacamole',
        calorias: 160,
        proteinas: 2,
        carbohidratos: 9,
        grasas: 15,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_mexicana',
        icono: 'guacamole',
        color: '#10B981',
      ),

      // ========== COMIDAS RÁPIDAS ==========
      _crearAlimento(
        nombre: 'Pizza de pepperoni',
        calorias: 266,
        proteinas: 11,
        carbohidratos: 33,
        grasas: 10,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_rapida',
        icono: 'pizza',
        color: '#DC2626',
      ),
      _crearAlimento(
        nombre: 'Hamburguesa con queso',
        calorias: 295,
        proteinas: 17,
        carbohidratos: 24,
        grasas: 14,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_rapida',
        icono: 'hamburger',
        color: '#92400E',
      ),
      _crearAlimento(
        nombre: 'Hot dog',
        calorias: 290,
        proteinas: 11,
        carbohidratos: 25,
        grasas: 16,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_rapida',
        icono: 'hotdog',
        color: '#F59E0B',
      ),
      _crearAlimento(
        nombre: 'Papas fritas',
        calorias: 312,
        proteinas: 3.4,
        carbohidratos: 41,
        grasas: 15,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_rapida',
        icono: 'fries',
        color: '#FDE68A',
      ),
      _crearAlimento(
        nombre: 'Nuggets de pollo',
        calorias: 296,
        proteinas: 15,
        carbohidratos: 18,
        grasas: 18,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'comida_rapida',
        icono: 'nuggets',
        color: '#F59E0B',
      ),

      // ========== BEBIDAS ==========
      _crearAlimento(
        nombre: 'Café americano',
        calorias: 2,
        proteinas: 0.3,
        carbohidratos: 0,
        grasas: 0,
        cantidad: 100,
        unidad: 'ml',
        categoria: 'bebidas',
        icono: 'coffee',
        color: '#78350F',
      ),
      _crearAlimento(
        nombre: 'Café con leche',
        calorias: 38,
        proteinas: 2,
        carbohidratos: 4.5,
        grasas: 1.5,
        cantidad: 100,
        unidad: 'ml',
        categoria: 'bebidas',
        icono: 'latte',
        color: '#92400E',
      ),
      _crearAlimento(
        nombre: 'Jugo de naranja natural',
        calorias: 45,
        proteinas: 0.7,
        carbohidratos: 10,
        grasas: 0.2,
        cantidad: 100,
        unidad: 'ml',
        categoria: 'bebidas',
        icono: 'juice',
        color: '#F97316',
      ),
      _crearAlimento(
        nombre: 'Refresco de cola',
        calorias: 41,
        proteinas: 0,
        carbohidratos: 10.6,
        grasas: 0,
        cantidad: 100,
        unidad: 'ml',
        categoria: 'bebidas',
        icono: 'soda',
        color: '#1F2937',
      ),
      _crearAlimento(
        nombre: 'Agua de jamaica',
        calorias: 37,
        proteinas: 0,
        carbohidratos: 9,
        grasas: 0,
        cantidad: 100,
        unidad: 'ml',
        categoria: 'bebidas',
        icono: 'jamaica',
        color: '#DC2626',
      ),
      _crearAlimento(
        nombre: 'Agua de horchata',
        calorias: 68,
        proteinas: 0.6,
        carbohidratos: 16,
        grasas: 0.5,
        cantidad: 100,
        unidad: 'ml',
        categoria: 'bebidas',
        icono: 'horchata',
        color: '#FBBF24',
      ),
      _crearAlimento(
        nombre: 'Licuado de fresa',
        calorias: 87,
        proteinas: 3,
        carbohidratos: 16,
        grasas: 1.5,
        cantidad: 100,
        unidad: 'ml',
        categoria: 'bebidas',
        icono: 'smoothie',
        color: '#EC4899',
      ),

      // ========== POSTRES ==========
      _crearAlimento(
        nombre: 'Pastel de chocolate',
        calorias: 371,
        proteinas: 4.9,
        carbohidratos: 51,
        grasas: 17,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'postres',
        icono: 'cake',
        color: '#78350F',
      ),
      _crearAlimento(
        nombre: 'Helado de vainilla',
        calorias: 207,
        proteinas: 3.5,
        carbohidratos: 24,
        grasas: 11,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'postres',
        icono: 'ice_cream',
        color: '#FEF3C7',
      ),
      _crearAlimento(
        nombre: 'Galletas de avena',
        calorias: 471,
        proteinas: 6,
        carbohidratos: 66,
        grasas: 20,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'postres',
        icono: 'cookie',
        color: '#92400E',
      ),
      _crearAlimento(
        nombre: 'Flan napolitano',
        calorias: 218,
        proteinas: 5,
        carbohidratos: 35,
        grasas: 6,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'postres',
        icono: 'flan',
        color: '#FDE68A',
      ),
      _crearAlimento(
        nombre: 'Gelatina',
        calorias: 62,
        proteinas: 1.6,
        carbohidratos: 14,
        grasas: 0,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'postres',
        icono: 'jello',
        color: '#DC2626',
      ),

      // ========== DESAYUNOS ==========
      _crearAlimento(
        nombre: 'Cereal con leche',
        calorias: 152,
        proteinas: 5,
        carbohidratos: 28,
        grasas: 2.5,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'desayunos',
        icono: 'cereal',
        color: '#F59E0B',
      ),
      _crearAlimento(
        nombre: 'Pancakes con miel',
        calorias: 227,
        proteinas: 6,
        carbohidratos: 44,
        grasas: 3,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'desayunos',
        icono: 'pancakes',
        color: '#FDE68A',
      ),
      _crearAlimento(
        nombre: 'Waffles',
        calorias: 291,
        proteinas: 8,
        carbohidratos: 37,
        grasas: 13,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'desayunos',
        icono: 'waffle',
        color: '#FDE047',
      ),
      _crearAlimento(
        nombre: 'Molletes con frijol',
        calorias: 195,
        proteinas: 8,
        carbohidratos: 32,
        grasas: 3,
        cantidad: 100,
        unidad: 'gramos',
        categoria: 'desayunos',
        icono: 'mollete',
        color: '#92400E',
      ),
    ];
  }

  static AlimentoBase _crearAlimento({
    required String nombre,
    required double calorias,
    required double proteinas,
    required double carbohidratos,
    required double grasas,
    required double cantidad,
    required String unidad,
    String? categoria,
    String? icono,
    String? color,
  }) {
    return AlimentoBase()
      ..nombre = nombre
      ..calorias = calorias
      ..proteinas = proteinas
      ..carbohidratos = carbohidratos
      ..grasas = grasas
      ..cantidadReferencia = cantidad
      ..unidadReferencia = unidad
      ..categoria = categoria
      ..icono = icono
      ..color = color;
  }
}
